# Ejercicio 4

In [21]:
ColabNotebook = 'google.colab' in str(get_ipython())

if ColabNotebook: # maquina virtual colab
    # monta G-drive en entorno COLAB
    from google.colab import drive
    drive.mount('/content/drive/')

    # carpeta donde se encuentran archivos .py auxiliares
    FUENTES_DIR  = '/content/drive/MyDrive/Colab Notebooks/FUENTES/'
    DATOS_DIR    = '/content/drive/MyDrive/Colab Notebooks/DATOS/'      # carpeta donde se encuentran los datasets
    MODELOS_DIR  = '/content/drive/MyDrive/Colab Notebooks/MODELOS/'    # carpeta donde se encuentran los modelos
    ARCHIVOS_DIR = '/content/drive/MyDrive/Colab Notebooks/ARCHIVOS/'   # carpeta recuperar o copiar archivos
else: # maquina local ipython
    # configuración para notebook con instalación LOCAL
    FUENTES_DIR  = '../Fuentes/'     # carpeta donde se encuentran archivos .py auxiliares
    DATOS_DIR    = '../Datos/'      # carpeta donde se encuentran los datasets
    MODELOS_DIR  = '../Modelos/'    # carpeta donde se encuentran los modelos
    ARCHIVOs_DIR = '../Archivos/'   # carpeta recuperar o copiar archivos

# agrega ruta de busqueda donde tenemos archivos .py
import sys
sys.path.append(FUENTES_DIR)

In [30]:
FUENTES_DIR  = '../Fuentes/'     # carpeta donde se encuentran archivos .py auxiliares
DATOS_DIR    = '../Datos/'      # carpeta donde se encuentran los datasets
MODELOS_DIR  = '../Modelos/'    # carpeta donde se encuentran los modelos
ARCHIVOs_DIR = '../Archivos/'   # carpeta recuperar o copiar archivos

# agrega ruta de busqueda donde tenemos archivos .py
import sys
sys.path.append(FUENTES_DIR)

Se busca predecir si el tipo de fármaco que se debe administrar a un paciente afectado de rinitis alérgica es 
el habitual o no. Se dispone de información correspondiente a las historias clínicas de pacientes atendidos 
previamente. Las variables relevadas son las siguientes:
- Age: Edad
- Sex: Sexo
-  BP (Blood Pressure): Presión sanguínea.
-  Cholesterol: nivel de colesterol.
-  Na: Nivel de sodio en la sangre.
- K: Nivel de potasio en la sangre.
- Class: Fármaco suministrado. Cada paciente 
ha sido medicado con un único fármaco de 5 
posibles: DrugA, DrugB, DrugC, DrugX, DrugY

In [16]:
import pandas as pd      # para trabajar con archivos de datos csv, excel, etc: https://pandas.pydata.org/docs/getting_started/tutorials.html
import chardet           # para detectar la codificación de texto en archivos


nombre_archivo = DATOS_DIR + 'Drug5.csv' # archivo de hojas

#-- detectando la codificación de caracteres usada ----
with open(nombre_archivo, 'rb') as f:
    result = chardet.detect(f.read())  # or readline if the file is large

# recupera el archivo en un objeto dataframe de pandas utilizando la codificación detectada
df = pd.read_csv(nombre_archivo, encoding=result['encoding'])

# visualiza el dataframe

display(df)

     Age Sex      BP Cholesterol        Na         K   Drug
0     23   F    HIGH        HIGH  0.792535  0.031258  drugY
1     47   M     LOW        HIGH  0.739309  0.056468  drugC
2     47   M     LOW        HIGH  0.697269  0.068944  drugC
3     28   F  NORMAL        HIGH  0.563682  0.072289  drugX
4     61   F     LOW        HIGH  0.559294  0.030998  drugY
..   ...  ..     ...         ...       ...       ...    ...
195   56   F     LOW        HIGH  0.848774  0.073380  drugC
196   16   M     LOW        HIGH  0.743021  0.061886  drugC
197   52   M  NORMAL        HIGH  0.549945  0.055581  drugX
198   23   M  NORMAL      NORMAL  0.784520  0.055959  drugX
199   40   F     LOW      NORMAL  0.683503  0.060226  drugX

[200 rows x 7 columns]

DIVISION DEL DATSET EN CONJUNTOS DE ENTRENAMIENTO Y PRUEBA

In [34]:
from sklearn.model_selection import train_test_split
X = df.drop('Drug', axis=1)  # Variables independientes
y = df['Drug']  # Variable dependiente

In [32]:
from ClassPerceptron import Perceptron
from sklearn import model_selection,preprocessing
import pandas as pd
import numpy as np
from matplotlib import pylab as plt

NORMALIZACION

In [33]:
#-- ordinales a numericos ---
mapeo = {'Sex': {'F':1, 'M':0},
          'BP':{'HIGH':2, 'NORMAL':1, 'LOW':0},
          'Cholesterol':{'NORMAL':0, 'HIGH':1}}

X.replace(mapeo, inplace=True)
X

     Age  Sex  BP  Cholesterol        Na         K
0     23    1   2            1  0.792535  0.031258
1     47    0   0            1  0.739309  0.056468
2     47    0   0            1  0.697269  0.068944
3     28    1   1            1  0.563682  0.072289
4     61    1   0            1  0.559294  0.030998
..   ...  ...  ..          ...       ...       ...
195   56    1   0            1  0.848774  0.073380
196   16    0   0            1  0.743021  0.061886
197   52    0   1            1  0.549945  0.055581
198   23    0   1            0  0.784520  0.055959
199   40    1   0            0  0.683503  0.060226

[200 rows x 6 columns]

In [39]:
y

0      drugY
1      drugC
2      drugC
3      drugX
4      drugY
       ...
195    drugC
196    drugC
197    drugX
198    drugX
199    drugX
Name: Drug, Length: 200, dtype: object

In [40]:

y = y.apply(lambda x: 1 if x == 'drugY' else 0)
y

0      1
1      0
2      0
3      0
4      1
      ..
195    0
196    0
197    0
198    0
199    0
Name: Drug, Length: 200, dtype: int64

In [44]:
X_train = X_train.astype(float)

ValueError: could not convert string to float: 'F'

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [42]:
normalizarEntrada = 1  # 1 si normaliza; 0 si no
if normalizarEntrada:
    #--- Normalización lineal entre 0 y 1 ---
    normalizador = preprocessing.MinMaxScaler()

    # Normaliza utilizando la media y el desvio
    # normalizador= preprocessing.StandardScaler()
    
    X_train = normalizador.fit_transform(X_train)
    X_test  = normalizador.transform(X_test)

ValueError: could not convert string to float: 'F'

a) Utilice el archivo Drug_train.csv para entrenar un perceptrón que sea capaz de predecir si el tipo de 
fármaco que se debe administrar a un paciente afectado de rinitis alérgica es el habitual (suministro de 
DrugY) o no.

- HABITUAL --> DrugY
- no habitual

b)  Luego utilice el archivo Drug_test.csv para medir la calidad del modelo.

c) Resuelva el problema:
- numerizando los atributos ordinales utilizando dos representaciones diferentes: como entero único 
y de manera binaria (dummy).
- Normalizando de diferentes formas: Sin normalizar, normalización lineal, normalización con media y 
desvío